### ISSUE TITLE
getting error during ant run build in unix

### ISSUE THREAD

**Issue by shahid-khans** [PanJiaChen/vue-admin-template#204]
(node:11148) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'search' of undefined
    at /home/shahid/vue-admin-template/static/css/chunk-elementUI.e8091cad.css:1:155209
    at isValueCustomProp (/home/shahid/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:106:45)
    at /home/shahid/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:449:18
    at mergeRules (/home/shahid/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/mergeRules.js:46:17)
    at wsc.forEach (/home/shahid/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:438:34)
    at Array.forEach (<anonymous>)
    at Object.merge (/home/shahid/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:436:9)
    at _decl2.default.forEach.p (/home/shahid/vue-admin-template/node_modules/postcss-merge-longhand/dist/index.js:22:19)
    at Array.forEach (<anonymous>)
    at css.walkRules.rule (/home/shahid/vue-admin-template/node_modules/postcss-merge-longhand/dist/index.js:20:28)
    at /home/shahid/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:239:18
    at /home/shahid/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:135:18
    at Root.each (/home/shahid/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/home/shahid/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:131:17)
    at Root.walkRules (/home/shahid/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:237:19)
    at css (/home/shahid/vue-admin-template/node_modules/postcss-merge-longhand/dist/index.js:19:13)
    at initializePlugin (/home/shahid/vue-admin-template/node_modules/cssnano/dist/index.js:35:51)
(node:11148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11148) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1222
