### ISSUE TITLE
未更改的模板代码`npm run build` 失败

### ISSUE THREAD

**Issue by Yansongsongsong** [PanJiaChen/vue-admin-template#206]
复现：
```
git clone https://github.com/PanJiaChen/vue-admin-template.git
npm run install
npm run build
```
错误信息
```
(node:48048) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'search' of undefined
    at /Users/user/test/vue-admin-template/static/css/chunk-elementUI.e8091cad.css:1:155209
    at isValueCustomProp (/Users/user/test/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:106:45)
    at /Users/user/test/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:449:18
    at mergeRules (/Users/user/test/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/mergeRules.js:46:17)
    at wsc.forEach (/Users/user/test/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:438:34)
    at Array.forEach (<anonymous>)
    at Object.merge (/Users/user/test/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:436:9)
    at _decl2.default.forEach.p (/Users/user/test/vue-admin-template/node_modules/postcss-merge-longhand/dist/index.js:22:19)
    at Array.forEach (<anonymous>)
    at css.walkRules.rule (/Users/user/test/vue-admin-template/node_modules/postcss-merge-longhand/dist/index.js:20:28)
    at /Users/user/test/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:239:18
    at /Users/user/test/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:135:18
    at Root.each (/Users/user/test/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/user/test/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:131:17)
    at Root.walkRules (/Users/user/test/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:237:19)
    at css (/Users/user/test/vue-admin-template/node_modules/postcss-merge-longhand/dist/index.js:19:13)
    at initializePlugin (/Users/user/test/vue-admin-template/node_modules/cssnano/dist/index.js:35:51)
(node:48048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:48048) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

build失败请问是什么原因呢
@canghai908 @Armour @PanJiaChen 
打扰啦

**Comment by Yansongsongsong** [comment]
PanJiaChen/vue-element-admin#1222
已经解决，谢谢大佬~

**Comment by Yansongsongsong** [comment]
PanJiaChen/vue-element-admin#1222
已经解决，谢谢大佬~

**Comment by Yansongsongsong** [comment]
github 除了bug吧。。
