### ISSUE TITLE
感谢您的模板

### ISSUE THREAD

**Issue by zwj242647** [PanJiaChen/vue-admin-template#212]
在自己学习前端的知识，接触到您的框架和教程，感觉很不错。但是npm install后没有办法run起来,您能抽空检查下么，十分感谢！

**Comment by PanJiaChen** [comment]
你都不贴 错误信息 怎么帮你？

**Comment by jinggoing** [comment]
以下是错误信息

 vue-admin-template git:(master) npm run dev

> vue-admin-template@3.8.0 dev /Users/jinxiong/GitHub/vue-admin-template
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 10% building modules 1/1 modules 0 activeevents.js:136
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 172.16.100.53:9528
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1523:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:102:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-admin-template@3.8.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-admin-template@3.8.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by yixius** [comment]
Error: listen EADDRNOTAVAIL 172.16.100.53:9528
Error Address Not Available ，有可能端口被占用了吧
