### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by Sherry233** [PanJiaChen/vue-admin-template#363]
环境 -- Windows+ node8.1.2
现象 -- 直接clone项目跑npm install之后跑npm run dev报错 （未修改过代码）
D:\install\vue-admin-template\node_modules\@vue\cli-service\node_modules\read-pkg\index.js:13
                ...options
                ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\install\vue-admin-template\node_modules\@vue\cli-service\lib\Service.js:5:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-admin-template@4.1.0 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-admin-template@4.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
![image](https://user-images.githubusercontent.com/28591257/57501579-b08ec000-731a-11e9-80f5-875b68cd88c6.png)

**Comment by PanJiaChen** [comment]
请确定自己的依赖是否有正确安装。

**Comment by zaofanjun** [comment]
我也是run dev就报错，依赖都用cnpm重装好几遍了

**Comment by zaofanjun** [comment]
牛逼了，用 sudo npm run dev启动就可以了
mac系统

**Comment by Sherry233** [comment]
可能是node版本和依赖的包的版本之间有问题，node8  将报错的包换成3.5.3的版本
