### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by wanbing1986** [PanJiaChen/vue-admin-template#384]
> vue-admin-template@4.2.1 dev /Volumes/project/pmps/vueweb
> vue-cli-service serve

 INFO  Starting development server...
 10% building 2/2 modules 0 active ERROR  SyntaxError: Unexpected string     
/Volumes/project/pmps/vueweb/mock/index.js:1
(function (exports, require, module, __filename, __dirname) { import "**core-js/modules/es6.regexp.constructor**";
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._compile (/Volumes/project/pmps/vueweb/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/Volumes/project/pmps/vueweb/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at registerRoutes (/Volumes/project/pmps/vueweb/mock/mock-server.js:10:30)
    at Object.module.exports.app [as after] (/Volumes/project/pmps/vueweb/mock/mock-server.js:41:22)
    at Server.setupAfterFeature (/Volumes/project/pmps/vueweb/node_modules/webpack-dev-server/lib/Server.js:441:18)
    at Object.after (/Volumes/project/pmps/vueweb/node_modules/webpack-dev-server/lib/Server.js:501:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-admin-template@4.2.1 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-admin-template@4.2.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wanb/.npm/_logs/2019-05-29T14_10_17_626Z-debug.log

![image](https://user-images.githubusercontent.com/47131261/58564346-57ea7d00-825f-11e9-9d2c-5508f71e4ac5.png)

**Comment by fya0122** [comment]
巧了，我也是这样的错啊！

**Comment by dingwen1** [comment]
怎么样。 解决了吗？

**Comment by dingwen1** [comment]
我将vue.config.js中47行mock的引入注释掉了。 就好了

**Comment by wanbing1986** [comment]
> 我将vue.config.js中47行mock的引入注释掉了。 就好了

谢谢，确实可以运行了

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy (/Volumes/project/pmps/vueweb/node_modules/eslint/lib/config.js:268:39)
    at Config.getConfigHierarchy (/Volumes/project/pmps/vueweb/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/Volumes/project/pmps/vueweb/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/Volumes/project/pmps/vueweb/node_modules/eslint/lib/config.js:342:29)
    at processText (/Volumes/project/pmps/vueweb/node_modules/eslint/lib/cli-engine.js:181:33)
    at CLIEngine.executeOnText (/Volumes/project/pmps/vueweb/node_modules/eslint/lib/cli-engine.js:690:40)
    at lint (/Volumes/project/pmps/vueweb/node_modules/eslint-loader/index.js:263:17)
    at transform (/Volumes/project/pmps/vueweb/node_modules/eslint-loader/index.js:237:18)
    at /Volumes/project/pmps/vueweb/node_modules/loader-fs-cache/index.js:127:18
    at ReadFileContext.callback (/Volumes/project/pmps/vueweb/node_modules/loader-fs-cache/index.js:31:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:238:13)


这个错误知道什么问题吗

**Comment by wxb1123603312** [comment]
老哥你问题解决了吗 怎么解决的我也遇到过了

**Comment by zgsnbtl** [comment]
> 老哥你问题解决了吗怎么解决的我也遇到过了

vue.config.js中open：true注释掉就可以了。

**Comment by zgsnbtl** [comment]
vue.config.js中open：true注释掉就可以了

**Comment by zgsnbtl** [comment]
> 老哥你问题解决了吗怎么解决的我也遇到过了

vue.config.js中open：true注释掉就可以了

**Comment by zgsnbtl** [comment]
vue.config.js中open：true注释掉就可以了

**Comment by airzhanglin** [comment]
> 我将vue.config.js中47行mock的引入注释掉了。 就好了

注释掉之后无法登录了吧，这个怎么解决

**Comment by Lucky-dj** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/2008

**Comment by qq814504797** [comment]
我想知道为什么会有这个报错
