### ISSUE TITLE
npm run dev Unexpected token import 错误

### ISSUE THREAD

**Issue by dboy1981** [PanJiaChen/vue-admin-template#386]
INFO  Starting development server...
 10% building 2/2 modules 0 active ERROR  SyntaxError: Unexpected token import
/Users/dboy/Documents/Works/Release/NodeSites/admin.cs.xdg.com/mock/index.js:1
(function (exports, require, module, __filename, __dirname) { import "core-js/modules/es6.regexp.constructor";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Module._compile (/Users/dboy/Documents/Works/Release/NodeSites/admin.cs.xdg.com/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (/Users/dboy/Documents/Works/Release/NodeSites/admin.cs.xdg.com/node_modules/pirates/lib/index.js:104:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at registerRoutes (/Users/dboy/Documents/Works/Release/NodeSites/admin.cs.xdg.com/mock/mock-server.js:10:30)
    at Object.module.exports.app [as after] (/Users/dboy/Documents/Works/Release/NodeSites/admin.cs.xdg.com/mock/mock-server.js:41:22)
    at Object.after (/Users/dboy/Documents/Works/Release/NodeSites/admin.cs.xdg.com/node_modules/webpack-dev-server/lib/Server.js:519:19)
    at Server.forEach (/Users/dboy/Documents/Works/Release/NodeSites/admin.cs.xdg.com/node_modules/webpack-dev-server/lib/Server.js:582:24)
    at Array.forEach (<anonymous>)

**Comment by mrjlovetian** [comment]
I also encountered the same problem

**Comment by sweetienianyu** [comment]
I also encountered the same problem

**Comment by LucaLJX** [comment]
这个怎么解决
