### ISSUE TITLE
Windows 下运行报错：SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by yingw** [PanJiaChen/vue-admin-template#512]
WIndows 下 run dev 会报错：
```
C:\Users\yinguowei\Projects\vue-admin-template>npm run dev

> vue-admin-template@4.2.1 dev C:\Users\yinguowei\Projects\vue-admin-template
> vue-cli-service serve

 INFO  Starting development server...
 10% building 2/2 modules 0 active ERROR  SyntaxError: Cannot use import statement outside a module
D:\Users\yinguowei\Projects\vue-admin-template\mock\index.js:1
import {Mock} from 'mockjs'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Module._compile (D:\Users\yinguowei\Projects\vue-admin-template\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.newLoader [as .js] (D:\Users\yinguowei\Projects\vue-admin-template\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at registerRoutes (D:\Users\yinguowei\Projects\vue-admin-template\mock\mock-server.js:10:30)
    at Object.module.exports [as after] (D:\Users\yinguowei\Projects\vue-admin-template\mock\mock-server.js:41:22)
    at Server.setupAfterFeature (D:\Users\yinguowei\Projects\vue-admin-template\node_modules\webpack-dev-server\lib\Server.js:431:18)
    at Object.after (D:\Users\yinguowei\Projects\vue-admin-template\node_modules\webpack-dev-server\lib\Server.js:491:16)
    at D:\Users\yinguowei\Projects\vue-admin-template\node_modules\webpack-dev-server\lib\Server.js:550:24
    at Array.forEach (<anonymous>)
    at Server.setupFeatures (D:\Users\yinguowei\Projects\vue-admin-template\node_modules\webpack-dev-server\lib\Server.js:549:49)
    at new Server (D:\Users\yinguowei\Projects\vue-admin-template\node_modules\webpack-dev-server\lib\Server.js:125:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-admin-template@4.2.1 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-admin-template@4.2.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yinguowei\AppData\Roaming\npm-cache\_logs\2019-11-15T04_07_28_153Z-debug.log

```

![image](https://user-images.githubusercontent.com/1177503/68916761-59bee300-07a2-11ea-87b0-d7ed87f341ba.png)

环境是： Windows 10 ，新安装的 Node 12，淘宝源

又测试了一下 vue-element-admin，两个项目4.x版本都是一样这个错。

Google 了：https://github.com/PanJiaChen/vue-element-admin/issues/2681  ，修改了配置文件为 true （默认 false），还是一样。

最后试了 Ubuntu 和 Windows 的WSL Ubuntu，是好的。另外在 Windows 下测试了 3.11 的版本，也没问题。。。

**Comment by whiteworker** [comment]
+1
windows下
vue-cli 不支持es6的import 和export
centos可以支持

**Comment by hi500** [comment]
windows下如何解决啊
