### ISSUE TITLE
安装 fsevents报错 'CoreServices/CoreServices.h' file not found 

### ISSUE THREAD

**Issue by blakelu** [PanJiaChen/vue-admin-template#537]
@vue/cli 3.6.3
node v12.14.0
npm 6.13.4
macOS 10.15.2
xcode  11.3

>fsevents@1.2.11 install /Users/luxiaowei/gitRepository/zhenmeat_crm/vue->admin/node_modules/fsevents
>node-gyp rebuild
>
>SOLINK_MODULE(target) Release/.node
>CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc:10:10: fatal error: 'CoreServices/CoreServices.h' file not found
>#include "CoreServices/CoreServices.h"
>^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>../fsevents.cc:10:10: note: did not find header 'CoreServices.h' in framework
'CoreServices' (loaded from '/System/Library/Frameworks')
>1 error generated.
>make: *** [Release/obj.target/fse/fsevents.o] Error 1
>gyp ERR! build error
>gyp ERR! stack Error: make failed with exit code: 2
>gyp ERR! stack at ChildProcess.onExit > (/usr/local/Cellar/node/11.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
>gyp ERR! stack at ChildProcess.emit (events.js:189:13)
>gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
>gyp ERR! System Darwin 19.2.0
>gyp ERR! command "/usr/local/Cellar/node/11.11.0/bin/node" "/usr/local/Cellar/node/11.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
>gyp ERR! cwd /Users/luxiaowei/gitRepository/zhenmeat_crm/vue-admin/node_modules/fsevents
>gyp ERR! node -v v12.14.0
>gyp ERR! node-gyp -v v5.0.5
>gyp ERR! not ok
>npm notice created a lockfile as package-lock.json. You should commit this file.
>npm WARN vue-admin-template@4.2.1 No repository field.
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 install: node-gyp rebuild
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by blakelu** [comment]
用yarn 更新所有的包即可解决
