### ISSUE TITLE
npm run dev出错

### ISSUE THREAD

**Issue by Tarems** [PanJiaChen/vue-admin-template#545]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-admin-template@4.2.1~predev: vue-admin-template@4.2.1
6 info lifecycle vue-admin-template@4.2.1~dev: vue-admin-template@4.2.1
7 verbose lifecycle vue-admin-template@4.2.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue-admin-template@4.2.1~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\A Project\Vue\vue-admin-template\node_modules\.bin;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Program Files\TortoiseSVN\bin;D:\Program Files\Java\jdk1.8.0_181\bin;D:\Program Files\apache-maven-3.6.1\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\54157\AppData\Local\Microsoft\WindowsApps;d:\Program Files\Bandizip\;C:\Users\54157\AppData\Local\BypassRuntm;C:\Users\54157\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\54157\AppData\Roaming\npm
9 verbose lifecycle vue-admin-template@4.2.1~dev: CWD: D:\A Project\Vue\vue-admin-template
10 silly lifecycle vue-admin-template@4.2.1~dev: Args: [ '/d /s /c', 'vue-cli-service serve' ]
11 silly lifecycle vue-admin-template@4.2.1~dev: Returned: code: 1  signal: null
12 info lifecycle vue-admin-template@4.2.1~dev: Failed to exec dev script
13 verbose stack Error: vue-admin-template@4.2.1 dev: `vue-cli-service serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid vue-admin-template@4.2.1
15 verbose cwd D:\A Project\Vue\vue-admin-template
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v12.14.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error vue-admin-template@4.2.1 dev: `vue-cli-service serve`
22 error Exit status 1
23 error Failed at the vue-admin-template@4.2.1 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Tarems** [comment]
将%SystemRoot%\system32加入path变量中
解决：找到xxxx程序所在的路径，将该路径加入到path变量中，问题解决，若没有，可能要重启一下电脑
