### ISSUE TITLE
run不起来。。。

### ISSUE THREAD

**Issue by smarttang** [PanJiaChen/vue-admin-template#577]
Module Warning (from ./node_modules/eslint-loader/index.js):
error: Attribute ":class" should go before "class" (vue/attributes-order) at src/layout/components/Sidebar/Logo.vue:2:39:
  1 | <template>
> 2 |   <div class="sidebar-logo-container" :class="{'collapse':collapse}">
    |                                       ^
  3 |     <transition name="sidebarLogoFade">
  4 |       <router-link v-if="collapse" key="collapse" class="sidebar-logo-link" to="/">
  5 |         <img v-if="logo" :src="logo" class="sidebar-logo">

1 error found.
1 error potentially fixable with the `--fix` option.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Attribute "ref" should go before ":key" (vue/attributes-order) at src/views/login/index.vue:30:11:
  28 |         <el-input
  29 |           :key="passwordType"
> 30 |           ref="password"
     |           ^
  31 |           v-model="loginForm.password"
  32 |           :type="passwordType"
  33 |           placeholder="Password"

1 error found.
1 error potentially fixable with the `--fix` option.

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 
  App running at:
  - Local:   http://localhost:9529/ 
  - Network: http://192.168.31.126:9529/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

request invoke:/dev-api/vue-admin-template/user/info

**Comment by smarttang** [comment]
![image](https://user-images.githubusercontent.com/4961402/80869807-051e0e80-8cd5-11ea-88c6-0db091920c0c.png)

**Comment by jiaziteng** [comment]
你写的代码不符合eslint规范，想要关闭eslint规范，请去vue.config.js文件中将lintOnSave属性设为false
