### ISSUE TITLE
 error  in ./src/styles/index.scss

### ISSUE THREAD

**Issue by feeman89** [PanJiaChen/vue-admin-template#678]
![image](https://user-images.githubusercontent.com/65520943/118353959-3ba29080-b59b-11eb-80f8-2dbcb07f57ec.png)

**Comment by feeman89** [comment]
ERROR  Failed to compile with 2 errors                                                                                                                                                                                                                              下午4:34:35

 error  in ./src/styles/index.scss

Error: Missing binary. See message above.


 @ ./src/main.js 12:0-29
 @ multi ./src/main.js

 error  in ./src/views/404.vue?vue&type=style&index=0&id=c095f994&lang=scss&scoped=true&

Error: Missing binary. See message above.


 @ ./src/views/404.vue?vue&type=style&index=0&id=c095f994&lang=scss&scoped=true& 1:0-525 1:0-525
 @ ./src/views/404.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./src/main.js

 ERROR  Build failed with errors.
/Users/machao/Documents/app/el_ops/frontend/node_modules/runjs/lib/index.js:38
    throw new _common.RunJSError(error.message);
    ^

RunJSError: Command failed: vue-cli-service build --preview
    at runSync (/Users/machao/Documents/app/el_ops/frontend/node_modules/runjs/lib/index.js:38:11)
    at run (/Users/machao/Documents/app/el_ops/frontend/node_modules/runjs/lib/index.js:107:10)
    at Object.<anonymous> (/Users/machao/Documents/app/el_ops/frontend/build/index.js:10:3)
