### ISSUE TITLE
npm install 安装依赖失败，求解决方式

### ISSUE THREAD

**Issue by duchunqiu** [PanJiaChen/vue-admin-template#728]
![image](https://user-images.githubusercontent.com/79617287/163700866-330479eb-306f-44fd-9499-b7e017bdf222.png)
npm ERR! code 1
npm ERR! path D:\Git\project\vue-admin-template\node_modules\deasync
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.13.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.12 found at "C:\Users\zj\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\zj\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\zj\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\zj\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
npm ERR! gyp ERR! stack     at C:\Users\zj\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Users\zj\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm ERR! gyp ERR! stack     at C:\Users\zj\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\zj\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\zj\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\Git\project\vue-admin-template\node_modules\deasync
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zj\AppData\Local\npm-cache\_logs\2022-04-17T02_55_55_930Z-debug-0.log

**Comment by donghaoyi** [comment]
今天遇到了相同的问题，原因出在npm源上。切换到官方源`npm config set registry https://registry.npmjs.org/`，重新 npm i，依赖安装成功。

**Comment by tianjunguo** [comment]
> 今天遇到了相同的问题，原因出在npm源上。切换到官方源`npm config set registry https://registry.npmjs.org/`，重新 npm i，依赖安装成功。

不管用诶

**Comment by tianjunguo** [comment]
我的报错是这样
![image](https://user-images.githubusercontent.com/27934637/176815767-31367d6a-84ac-4e40-a091-4b9a873a3a23.png)

**Comment by Sunny-117** [comment]
加上这两个依赖：

<img width="902" alt="image" src="https://user-images.githubusercontent.com/73089592/199188196-2e995d19-6be8-4ad6-98ea-d3384c03ee8d.png">

然后用pnpm i安装，npm run dev后，会发现以下问题：https://github.com/PanJiaChen/vue-admin-template/issues/745
于是把这一行注释掉
<img width="960" alt="image" src="https://user-images.githubusercontent.com/73089592/199188356-3ff57564-fb17-42f4-8677-fec7b4d3ac7c.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/73089592/199188385-fc0efc79-c169-4500-828f-15ab371b2e4f.png">

可正常启动

**Comment by crxiang** [comment]
This dependency was not found:* svg-baker-runtime/browser-symbol in ./src/icons/svg/table.svg #745
这个问题只需要升级下svg-sprite-loader的版本到5.0.0以上就可以了
