### ISSUE TITLE
npm run dev 报错求解  vue-admin-template@4.4.0 dev | vue-cli-service serve | Node.js v18.15.0

### ISSUE THREAD

**Issue by w-jt** [PanJiaChen/vue-admin-template#763]
PS D:\wu\Desktop\project\vue-admin-template> npm run dev

> vue-admin-template@4.4.0 dev
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/5 modules 3 active ...\webpack-dev-server\client\index.js?http://192.168.1.30:9528&sockPath=/sockjs-nodeError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\wu\Desktop\project\vue-admin-template\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\wu\Desktop\project\vue-admin-template\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\wu\Desktop\project\vue-admin-template\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\wu\Desktop\project\vue-admin-template\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\wu\Desktop\project\vue-admin-template\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\wu\Desktop\project\vue-admin-template\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\wu\Desktop\project\vue-admin-template\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\wu\Desktop\project\vue-admin-template\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\wu\Desktop\project\vue-admin-template\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (D:\wu\Desktop\project\vue-admin-template\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (D:\wu\Desktop\project\vue-admin-template\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (D:\wu\Desktop\project\vue-admin-template\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\wu\Desktop\project\vue-admin-template\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\wu\Desktop\project\vue-admin-template\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\wu\Desktop\project\vue-admin-template\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\wu\Desktop\project\vue-admin-template\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\wu\Desktop\project\vue-admin-template\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\wu\Desktop\project\vue-admin-template\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\wu\Desktop\project\vue-admin-template\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\wu\Desktop\project\vue-admin-template\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\wu\Desktop\project\vue-admin-template\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\wu\Desktop\project\vue-admin-template\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\wu\Desktop\project\vue-admin-template\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\wu\Desktop\project\vue-admin-template\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\wu\Desktop\project\vue-admin-template\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0

**Comment by dudada2686357022** [comment]
node版本换成16的就好了

**Comment by wu67** [comment]
有几个依赖需要node v16, 差不多最高能用到14.14.2.  你用v18是跑不起来的. 而且这个模版已经几年没更新维护了. 
我们公司的一个后台项目就是用的这个模版, 我现在都着手替换成vite了
