### ISSUE TITLE
npm run dev失败

### ISSUE THREAD

**Issue by yyljwyy** [PanJiaChen/vue-admin-template#768]
执行后显示以下问题：
> vue-admin-template@4.4.0 dev
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/5 modules 3 active ...lint-loader\index.js??ref--13-0!E:\CodeRepos\vue-admin-template-master\src\main.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (E:\CodeRepos\vue-admin-template-master\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (E:\CodeRepos\vue-admin-template-master\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (E:\CodeRepos\vue-admin-template-master\node_modules\webpack\lib\NormalModule.js:471:10)
    at E:\CodeRepos\vue-admin-template-master\node_modules\webpack\lib\NormalModule.js:503:5
    at E:\CodeRepos\vue-admin-template-master\node_modules\webpack\lib\NormalModule.js:358:12
    at E:\CodeRepos\vue-admin-template-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\CodeRepos\vue-admin-template-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (E:\CodeRepos\vue-admin-template-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at E:\CodeRepos\vue-admin-template-master\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (E:\CodeRepos\vue-admin-template-master\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (E:\CodeRepos\vue-admin-template-master\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (E:\CodeRepos\vue-admin-template-master\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (E:\CodeRepos\vue-admin-template-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at E:\CodeRepos\vue-admin-template-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at E:\CodeRepos\vue-admin-template-master\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (E:\CodeRepos\vue-admin-template-master\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (E:\CodeRepos\vue-admin-template-master\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (E:\CodeRepos\vue-admin-template-master\node_modules\webpack\lib\NormalModule.js:471:10)
    at E:\CodeRepos\vue-admin-template-master\node_modules\webpack\lib\NormalModule.js:503:5
    at E:\CodeRepos\vue-admin-template-master\node_modules\webpack\lib\NormalModule.js:358:12
    at E:\CodeRepos\vue-admin-template-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\CodeRepos\vue-admin-template-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (E:\CodeRepos\vue-admin-template-master\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (E:\CodeRepos\vue-admin-template-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at E:\CodeRepos\vue-admin-template-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at E:\CodeRepos\vue-admin-template-master\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.1

**Comment by snowdream** [comment]
https://github.com/snowdreamtech/vue-admin-template/issues/2

https://stackoverflow.com/a/69699772

You can try one of these:

1. Downgrade to Node.js v16.

You can reinstall the current LTS version from Node.js’ [website](https://nodejs.org/en/download/releases/).

You can also use [nvm](https://github.com/nvm-sh/nvm). For Windows, use [nvm-windows](https://github.com/coreybutler/nvm-windows).

2. Enable legacy OpenSSL provider.

On Unix-like (Linux, macOS, Git bash, etc.):
```
export NODE_OPTIONS=--openssl-legacy-provider
```
On Windows command prompt:
```
set NODE_OPTIONS=--openssl-legacy-provider
```
On PowerShell:
```
$env:NODE_OPTIONS = "--openssl-legacy-provider"
```
